/**
 * @file class_file.hpp
 * @brief Declaration of the class file structure, as well as methods, fields and classes access flags
 */

#ifndef _CLASS_FILE_HPP
#define _CLASS_FILE_HPP

#include "attributes.hpp"

using namespace std;

//! Class Access Flags
#define ACC_PUBLIC     0x0001 // Declared public; may be accessed from outside its package
#define ACC_FINAL      0x0010 // Declared final; no subclasses allowed.
#define ACC_SUPER      0x0020 // Treat superclass methods specially when invoked by the invokespecial instruction.
#define ACC_INTERFACE  0x0200 // Is an interface, not a class.
#define ACC_ABSTRACT   0x0400 // Declared abstract; must not be instantiated
#define ACC_SYNTHETIC  0x1000 // Declared synthetic; not present in the source code.
#define ACC_ANNOTATION 0x2000 // Declared as an annotation type.
#define ACC_ENUM       0x4000 // Declared as an enum type.

//! Field Access and property flags
#define ACC_PUBLIC    0x0001 // Declared public; may be accessed from outside its package.
#define ACC_PRIVATE   0x0002 // Declared private; usable only within the defining class.
#define ACC_PROTECTED 0x0004 // Declared protected; may be accessed within Subclasses.
#define ACC_STATIC    0x0008 // Declared static.
#define ACC_FINAL     0x0010 // Declared final; never directly assigned to after Object construction.
#define ACC_VOLATILE  0x0040 // Declared volatile; cannot be cached.
#define ACC_TRANSIENT 0x0080 // Declared transient; not written or read by a persistent object manager.
#define ACC_SYNTHETIC 0x1000 // Declared synthetic; not present in the source code.
#define ACC_ENUM      0x4000 // Declared as an element of an enum.

//! Method Access and Property Flags
#define ACC_PUBLIC        0x0001 // Declared public; may be accessed from outside its package.
#define ACC_PRIVATE       0x0002 // Declared private; accessible only within the defining class.
#define ACC_PROTECTED     0x0004 // Declared protected; may be accessed withinsubclasses.
#define ACC_STATIC        0x0008 // Declared static.
#define ACC_FINAL         0x0010 // Declared final; must not be overridden.
#define ACC_SYNCHRONIZED  0x0020 // Declared synchronized; invocation is wrapped by a monitor use.
#define ACC_BRIDGE        0x0040 // A bridge method, generated by the compiler.
#define ACC_VARARGS       0x0080 // Declared with variable number of arguments.
#define ACC_NATIVE        0x0100 // Declared native; implemented in a language other than Java.
#define ACC_ABSTRACT      0x0400 // Declared abstract; no implementation is provided.
#define ACC_STRICT        0x0800 // Declared strictfp; floating-point mode is FP-strict.
#define ACC_SYNTHETIC     0x1000 // Declared synthetic; not present in the source code.

/**
 * @brief Attribute info structure. Contains values related to an attribute
 */
typedef struct attr_info {
    attr_info(ifstream &file);
    attr_info(bytestream_it &iterator);
    u2 attr_name_idx;
    u4 attr_length;
    vector<u1> info;
} attr_info;

/**
 * @brief The field info structure. Contains values related to a class field.
 * 
 */
typedef struct field_info {
    field_info(ifstream&, cp_info_vector&);
    u2 access_flags;
    u2 name_idx;
    u2 descriptor_idx;
    u2 attr_count;
    attr_info_vector attr;
} field_info;

/**
 * @brief The method info structure. Contains values related to a method;
 */
typedef struct method_info {
    method_info() = default;
    method_info(ifstream&, cp_info_vector&);
    u2 access_flags;
    u2 name_idx;
    u2 descriptor_idx;
    u2 attr_count;
    attr_info_vector attr;
} method_info;

/**
 * @brief The class file structure. Contains the components of a class.
 */
typedef struct class_file {
    u4 magic;
    u2 minor_version;
    u2 major_version;
    u2 constant_pool_count;
    cp_info_vector constant_pool;
    u2 access_flag;
    u2 this_class;
    u2 super_class;
    u2 interfaces_count;
    vector<u2> interfaces;
    u2 fields_count;
    vector<field_info> fields;
    u2 methods_count;
    vector<method_info> methods;
    u2 attributes_count;
    attr_info_vector attributes;
} class_file;

#endif // _CLASS_FILE_HPP